# Default user interface style "Dark" =================================================================
# You can put a copy of this file into the Little Navmap settings folder
# ("C:/Users/YOURUSERNAME/AppData/Roaming/ABarthel/" on Windows) to override the default settings.
#
# See https://www.littlenavmap.org/manuals/littlenavmap/release/latest/en/CUSTOMIZE.html for more information

[Options]
Version=3.1.0.develop

[StyleColors]
Active_AlternateBase=#232323
Active_Base=#141414
Active_BrightText=#fafafa
Active_Button=#232323
Active_ButtonText=#c8c8c8
Active_Dark=#050505
Active_Highlight=#2a82da
Active_HighlightedText=#000000
Active_Light=#555555
Active_Link=#2a82da
Active_LinkVisited=#2a82da
Active_Mid=#141414
Active_Midlight=#414141
Active_NoRole=#000000
Active_Shadow=#000000
Active_Text=#c8c8c8
Active_ToolTipBase=#232323
Active_ToolTipText=#c8c8c8
Active_Window=#0f0f0f
Active_WindowText=#c8c8c8
Disabled_AlternateBase=#232323
Disabled_Base=#141414
Disabled_BrightText=#fafafa
Disabled_Button=#414141
Disabled_ButtonText=#646464
Disabled_Dark=#050505
Disabled_Highlight=#2a82da
Disabled_HighlightedText=#000000
Disabled_Light=#555555
Disabled_Link=#2a82da
Disabled_LinkVisited=#2a82da
Disabled_Mid=#141414
Disabled_Midlight=#414141
Disabled_NoRole=#000000
Disabled_Shadow=#000000
Disabled_Text=#646464
Disabled_ToolTipBase=#232323
Disabled_ToolTipText=#c8c8c8
Disabled_Window=#0f0f0f
Disabled_WindowText=#646464
Inactive_AlternateBase=#232323
Inactive_Base=#141414
Inactive_BrightText=#fafafa
Inactive_Button=#232323
Inactive_ButtonText=#c8c8c8
Inactive_Dark=#050505
Inactive_Highlight=#2a82da
Inactive_HighlightedText=#000000
Inactive_Light=#555555
Inactive_Link=#2a82da
Inactive_LinkVisited=#2a82da
Inactive_Mid=#141414
Inactive_Midlight=#414141
Inactive_NoRole=#000000
Inactive_Shadow=#000000
Inactive_Text=#c8c8c8
Inactive_ToolTipBase=#232323
Inactive_ToolTipText=#c8c8c8
Inactive_Window=#0f0f0f
Inactive_WindowText=#c8c8c8
