openapi: 3.0.1
info:
  title: Little Navmap Web API
  description: ''
  version: 1.0.0
servers:
- url: http://localhost:8965/api
tags:
- name: Airport
  description: AirportActionsController
- name: Sim
  description: SimActionsController
- name: UI
  description: UiActionsController
paths:
  /airport/info:
    get:
      tags:
      - Airport
      summary: Get airport information by ICAO code
      operationId: airportInfoAction
      parameters:
      - name: ident
        required: true
        in: query
        description: Airport ICAO code
        schema:
          type: string
      responses:
        200:
          description: Airport information
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/AirportInfoResponse'                 
        400:
          description: Airport not found
          content: 
            text/plain:
              schema: 
                type: string
                example: "Airport not found" 
  /sim/info:
    get:
      tags:
      - Sim
      summary: Get active simulation information
      operationId: simInfoAction
      responses:
        200:
          description: Simulation information
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/SimInfoResponse'
  /ui/info:
    get:
      tags:
      - UI
      summary: Get UI information
      operationId: uiInfoAction
      responses:
        200:
          description: UI information
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/UiInfoResponse'
components:
  schemas:
    Coordinates:
      type: object
      description: Common coordinates type
      properties:
        lat:
          type: number
        lon:
          type: number
    AirportInfoResponse:
      type: object
      properties:
        activeDateTime:
          description: The active LNM time
          example: "Fr Jul 9 19:54:59 2021 GMT"
          type: string
          format: date-time
        activeDateTimeSource:
          description: The active LNM time source
          example:
            - "simulator date"
            - "real date"
          type: string
        city:
          description: The airports city
          example: "M체nchen"
          type: string
        closed:
          description: airport closed
          type: boolean
        com: 
          description: The airports available COM frequencies
          type: object
          properties:
            ATIS:
              type: number
              description: Only set if available. (Format 000,000 MHz)
              example: "123450"
            Tower:
              type: number
              description: Only set if available. (Format 000,000 MHz)
              example: "123450"
            AWOS:
              type: number
              description: Only set if available. (Format 000,000 MHz)
              example: "123450"
            ASOS:
              type: number
              description: Only set if available. (Format 000,000 MHz)
              example: "123450"
            UNICOM:
              type: number
              description: Only set if available. (Format 000,000 MHz)
              example: "123450"
        country: 
          description: The airports country
          type: string
          example: ""
        elevation: 
          description: The airports elevation in feet
          type: number
          example: "1468"
        facilities:
          description: Array of airport facilities/features
          type: array 
          items:
            type: string
            example:
              - "Aprons"
              - "Taxiways"
              - "ILS"
              - "Avgas"
              - "Jetfuel"
        iata: 
          description: The airports IATA code
          type: string
          example: ""
        icao: 
          description: The airports ICAO code
          type: string
          example: ""
        ident: 
          description: The airports ident (ICAO)
          type: string
          example: "EDDM"
        longestRunwayHeading: 
          description: The airports longest runway heading
          type: string
          example: "81째M, 261째M"
        longestRunwayLength: 
          description: The airports longest runway length in metres
          type: number
          example: "13106"
        longestRunwaySurface: 
          description: The airports longest runway surface
          type: string
          example:  "CE"
        longestRunwayWidth: 
          description: The airports longest runway width in metres
          type: number
          example: "188"
        magneticDeclination: 
          description: The airports magnetic variation/declination (+/East, -/West)
          type: number
          example: "1.9"
        metar: 
          description: The airports METAR weather reports
          type: object
          properties:
            simulator: 
              description: Only set if available
              type: object
              properties:
                nearest: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
                station: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
            activesky: 
              description: Only set if available
              type: object
              properties:
                nearest: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
                station: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
            noaa: 
              description: Only set if available
              type: object
              properties:
                nearest: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
                station: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
            vatsim: 
              description: Only set if available
              type: object
              properties:
                nearest: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
                station: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
            ivao: 
              description: Only set if available
              type: object
              properties:
                nearest: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
                station: 
                  type: string
                  example: "EDDM 091920Z 35005KT 320V020 9999 -SHRA FEW015 SCT025CB 16/14 Q1022 RESHRA NOSIG"
        name: 
          description: The airports name
          type: string
          example: "M체nchen"
        parking:
          description: The airports parking capacities
          type: object
          properties:
            gates:
              type: integer
              description: Only set if available
              format: int32
            jetWays: 
              type: integer
              description: Only set if available
              format: int32
            gaRamps: 
              type: integer
              description: Only set if available
              format: int32
            cargo: 
              type: integer
              description: Only set if available
              format: int32
            militaryCargo: 
              type: integer
              description: Only set if available
              format: int32
            militaryCombat: 
              type: integer
              description: Only set if available
              format: int32
            helipads: 
              type: integer
              description: Only set if available
              format: int32
        position: 
          description: The airports geographical position
          $ref: '#/components/schemas/Coordinates'
        rating: 
          description: The airports rating
          type: integer
          format: int32
        region: 
          description: The airports region
          type: string
          example: ""
        runways:
          description: Array of airport runway flags
          type: array
          items:
            type: string
            example: 
              - "Hard"
              - "Lighted"
        state: 
          description: The airports state/province
          type: string
          example: ""
        sunrise:
          description: The airports sunrise time
          type: string
          example: "02:40:40"
        sunset:
          description: The airports sunset time
          type: string
          example: "19:54:52"
        transitionAltitude:
          description: The airports transition altitude in feet
          type: number
          example: "5000"
    SimInfoResponse:
      type: object
      properties:
        active:
          type: boolean
        altitude_above_ground:
          description: "ft"
          type: number
          example: 1737.796875
        ground_altitude:
          description: "meters (?)"
          type: number
          example: 0.05364101380109787
        ground_speed:
          description: "kts"
          type: number
          example: 178.37759399414062
        heading:
          type: number
          example: 155.85145568847656
        indicated_altitude:
          description: "ft"
          type: number
          example: 1799.44482421875
        indicated_speed:
          description: "kts"
          type: number
          example: 173.4679718017578
        position:
          description: The user aircrafts geographical position
          $ref: '#/components/schemas/Coordinates'
        sea_level_pressure:
          description: "Mbar"
          type: number
          example: 1020
        simconnect_status:
          type: string
          example: "No error"
        true_airspeed:
          description: "kts"
          type: number
          example: 178.34288024902344
        vertical_speed:
          description: "fpm"
          type: number
          example: -4.088292598724365
    UiInfoResponse:
      type: object
      description: Common UI info
      properties:
        zoom_ui:
          description: the zoom value of the map inside LNM UI
          type: number
          example: 1803
        zoom_web:
          description: the zoom value of the map inside LNM Web UI
          type: number
          example: 1803